name: 测试 RSS 日报系统

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 运行单元测试
      run: |
        cd src
        python -m pytest tests/ -v
        
    - name: 测试 RSS 获取
      run: |
        cd src
        python rss_fetcher.py
        
    - name: 测试内容筛选
      run: |
        cd src
        python content_filter.py
        
    - name: 测试日报生成
      run: |
        cd src
        python daily_generator.py
        
    - name: 测试飞书发送（仅测试格式化）
      run: |
        cd src
        python feishu_sender.py 